name: Build & Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, synchronize, reopened]

env:
  BUILD_TYPE: Debug

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BW_OUT_DIR: bw-out
    steps:
    - uses: actions/checkout@v3
    - name: Install Clang and LLVM (including llvm-cov)
      uses: KyleMayes/install-llvm-action@v1.9.0
      with:
        version: "15.0.6"

    - name: Install sonar-scanner and build-wrapper
      uses: SonarSource/sonarcloud-github-c-cpp@v2

    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build \
              -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} \
              -DCMAKE_CXX_COMPILER=clang++

    - name: Build
      run: |
        build-wrapper-linux-x86-64 --out-dir ${{ env.BW_OUT_DIR }} \
           cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test
      working-directory: ${{github.workspace}}/build
      run: ./test/unit_tests

    - name: Merge counters from different runs and convert the result into an llvm-cov-compatible form
      working-directory: ${{github.workspace}}/build
      run: |
        llvm-profdata merge -o merged.profdata ${{github.workspace}}/build/*.profraw

    - name: Collect the coverage
      run: |
        llvm-cov show --show-branches=count --instr-profile merged.profdata test/unit_tests > coverage.txt

    - name: Run sonar-scanner
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      run: |
        sonar-scanner \
          --define sonar.cfamily.build-wrapper-output="${{ env.BW_OUT_DIR }}" \
          --define sonar.cfamily.llvm-cov.reportPath=coverage.txt
